name: contstimlang
channels:
  - pytorch
  - gurobi
  - ibmdecisionoptimization
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.7.6
  - cplex
  - pip
  - pytorch=1.3.1
  - pip:
    - gurobipy==9.5.1
    - jsonpickle==1.4.2
    - knlm==0.1.2
    - matplotlib==3.5.1
    - numpy==1.20.2
    - pandas==1.1.5
    - portalocker==2.0.0
    - requests==2.25.1
    - scikit-learn==1.0.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - statsmodels==0.12.2
    - tqdm==4.48.2
    - transformers==2.9.0